ALTER TABLE INFO DROP FOREIGN KEY FK_INFO_ROOM_ID
ALTER TABLE EXECUTOR DROP FOREIGN KEY FK_EXECUTOR_Controller_id
ALTER TABLE EXECUTOR DROP FOREIGN KEY FK_EXECUTOR_CATEGORY_ID
ALTER TABLE SENSOR DROP FOREIGN KEY FK_SENSOR_Controller_id
ALTER TABLE SENSOR DROP FOREIGN KEY FK_SENSOR_CATEGORY_ID
ALTER TABLE COMMAND DROP FOREIGN KEY FK_COMMAND_USER_ID
ALTER TABLE COMMAND DROP FOREIGN KEY FK_COMMAND_ROOM_ID
ALTER TABLE MESSAGE DROP FOREIGN KEY FK_MESSAGE_ROOM_ID
ALTER TABLE MESSAGE DROP FOREIGN KEY FK_MESSAGE_USER_ID
ALTER TABLE ROOM DROP FOREIGN KEY FK_ROOM_CONTROLLERS_ID
DROP TABLE INFO
DROP TABLE CATEGORY
DROP TABLE EXECUTOR
DROP TABLE SENSOR
DROP TABLE COMMAND
DROP TABLE MESSAGE
DROP TABLE USER
DROP TABLE CONTROLLER
DROP TABLE ROOM
